"use client";

import { useState } from "react";
import type { ScoutFinalReportsRow } from "@/types/database";

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function BrokerEmailDraft({ report }: { report: ScoutFinalReportsRow }) {
  const [open, setOpen] = useState(false);
  const [destination, setDestination] = useState("");
  const [copied, setCopied] = useState(false);

  const dest = destination.trim() || "your destination country";

  function buildEmailBody(): string {
    const lines: string[] = [];

    lines.push(`Subject: HS Code Verification Request — ${report.translated_name || report.product_name}`);
    lines.push("");
    lines.push("Dear Customs Broker,");
    lines.push("");
    lines.push(
      `I am planning to import the following product from South Korea and would appreciate your help verifying the classification and compliance requirements for import to ${dest}.`
    );
    lines.push("");

    lines.push("── PRODUCT INFORMATION ──");
    lines.push(`Product: ${report.translated_name || report.product_name}`);
    if (report.category?.trim()) lines.push(`Category: ${report.category}`);
    lines.push("");

    lines.push("── SUGGESTED CLASSIFICATION ──");
    lines.push(`HS Code: ${report.hs_code}`);
    if (report.hs_description?.trim()) lines.push(`Description: ${report.hs_description}`);
    if (report.status_reason?.trim()) lines.push(`Classification Basis: ${report.status_reason}`);
    lines.push("");

    const compLines: string[] = [];
    if (report.composition_info?.trim()) compLines.push(`Key Ingredients: ${report.composition_info}`);
    if (report.key_risk_ingredient?.trim()) compLines.push(`Risk Ingredients: ${report.key_risk_ingredient}`);

    let hazmatParsed: Record<string, boolean> | null = null;
    try {
      let h = report.hazmat_status;
      if (typeof h === "string") h = JSON.parse(h);
      if (typeof h === "string") h = JSON.parse(h);
      if (typeof h === "object" && h !== null) hazmatParsed = h as Record<string, boolean>;
    } catch {
      // ignore
    }

    if (hazmatParsed) {
      const flags: string[] = [];
      if (hazmatParsed.contains_liquid) flags.push("Liquid");
      if (hazmatParsed.contains_powder) flags.push("Powder");
      if (hazmatParsed.contains_battery) flags.push("Battery");
      if (hazmatParsed.contains_aerosol) flags.push("Aerosol/Pressurized");
      if (flags.length > 0) compLines.push(`Hazmat Flags: Contains ${flags.join(", ")}`);
    }

    if (compLines.length > 0) {
      lines.push("── COMPOSITION & HAZMAT ──");
      compLines.forEach((l) => lines.push(l));
      lines.push("");
    }

    if (report.required_certificates?.trim()) {
      lines.push("── CERTIFICATIONS ──");
      lines.push(`Required: ${report.required_certificates}`);
      lines.push("");
    }

    const specLines: string[] = [];
    if (report.dimensions_cm?.trim()) specLines.push(`Dimensions: ${report.dimensions_cm}`);
    if (report.actual_weight_g) specLines.push(`Weight: ${report.actual_weight_g}g`);
    if (specLines.length > 0) {
      lines.push("── PHYSICAL SPECS ──");
      specLines.forEach((l) => lines.push(l));
      lines.push("");
    }

    lines.push("Could you please confirm:");
    lines.push(`1. Is this HS code correct for import to ${dest}?`);
    lines.push("2. Are additional certifications or permits needed?");
    lines.push("3. Any duties or restrictions I should be aware of?");
    lines.push("");
    lines.push("Thank you for your assistance.");
    lines.push("");
    lines.push("---");
    lines.push(
      "⚠️ This data was compiled and translated from Korean sources by AI. Final verification by a licensed customs broker is legally required before export."
    );
    lines.push("");
    lines.push("Generated by K-Product Scout");
    if (report.image_url?.trim() || report.naver_link?.trim()) lines.push("");
    if (report.image_url?.trim()) lines.push(`Product Image: ${report.image_url}`);
    if (report.naver_link?.trim()) lines.push(`Reference Site: ${report.naver_link}`);

    return lines.join("\n");
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(buildEmailBody());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const bodyText = buildEmailBody();
  const highlightTerm = dest;
  const parts =
    highlightTerm === ""
      ? [bodyText]
      : bodyText.split(new RegExp(`(${escapeRegex(highlightTerm)})`, "gi"));

  return (
    <div>
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left p-5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 hover:bg-emerald-500/20 transition-colors flex flex-col items-start"
      >
        <div className="flex w-full justify-between items-center">
          <span className="text-lg font-bold text-emerald-400">Broker Email Draft</span>
          <span className="text-emerald-400/70 shrink-0">{open ? "▲" : "▼"}</span>
        </div>
        <p className="text-[11px] text-white/40 mt-1">
          *Includes English drafts for HS Code, Hazmat, and INCI lists for your broker.
        </p>
      </button>

      {open && (
        <div className="mt-3 p-4 rounded-xl border border-white/10 bg-white/[0.03]">
          <div className="mb-4">
            <label className="text-sm font-medium text-white/60 block mb-2">Destination Country</label>
            <input
              type="text"
              value={destination}
              onChange={(e) => setDestination(e.target.value)}
              placeholder="e.g. United States, Germany, Japan..."
              className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-base text-white placeholder:text-white/30 focus:outline-none focus:border-white/30"
            />
          </div>
          <pre className="text-xs text-white/50 whitespace-pre-wrap leading-relaxed max-h-64 overflow-y-auto mb-3 p-3 bg-black/30 rounded-lg">
            {parts.map((segment, i) =>
              i % 2 === 1 ? (
                <mark key={i} className="bg-amber-400/40 text-amber-200 font-bold rounded px-0.5">
                  {segment}
                </mark>
              ) : (
                segment
              )
            )}
          </pre>
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-lg bg-emerald-500 text-white text-sm font-semibold hover:bg-emerald-400 transition-colors"
          >
            {copied ? "✅ Copied!" : "📋 Copy Email Draft"}
          </button>
        </div>
      )}
    </div>
  );
}
